# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/image_process/Sobel/src/ip/Fifo_In8x1024_Out8x1024/Fifo_In8x1024_Out8x1024.xci
# IP: The module: 'Fifo_In8x1024_Out8x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/image_process/Sobel/src/ip/Fifo_In8x1024_Out8x1024/Fifo_In8x1024_Out8x1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_In8x1024_Out8x1024'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/image_process/Sobel/src/ip/Fifo_In8x1024_Out8x1024/Fifo_In8x1024_Out8x1024_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_In8x1024_Out8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/image_process/Sobel/src/ip/Fifo_In8x1024_Out8x1024/Fifo_In8x1024_Out8x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_In8x1024_Out8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/image_process/Sobel/src/ip/Fifo_In8x1024_Out8x1024/Fifo_In8x1024_Out8x1024.xci
# IP: The module: 'Fifo_In8x1024_Out8x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/image_process/Sobel/src/ip/Fifo_In8x1024_Out8x1024/Fifo_In8x1024_Out8x1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_In8x1024_Out8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/image_process/Sobel/src/ip/Fifo_In8x1024_Out8x1024/Fifo_In8x1024_Out8x1024_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_In8x1024_Out8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/image_process/Sobel/src/ip/Fifo_In8x1024_Out8x1024/Fifo_In8x1024_Out8x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_In8x1024_Out8x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
