######################################################################
#
# File name : tb_compile.do
# Created on: Sat Mar 18 18:14:41 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/xbip_utils_v3_0_9
vlib modelsim_lib/msim/c_reg_fd_v12_0_5
vlib modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_4
vlib modelsim_lib/msim/xbip_pipe_v3_0_5
vlib modelsim_lib/msim/xbip_dsp48_addsub_v3_0_5
vlib modelsim_lib/msim/xbip_addsub_v3_0_5
vlib modelsim_lib/msim/c_addsub_v12_0_12
vlib modelsim_lib/msim/xbip_bram18k_v3_0_5
vlib modelsim_lib/msim/mult_gen_v12_0_14
vlib modelsim_lib/msim/axi_utils_v2_0_5
vlib modelsim_lib/msim/cordic_v6_0_14
vlib modelsim_lib/msim/fifo_generator_v13_2_2

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap xpm modelsim_lib/msim/xpm
vmap xbip_utils_v3_0_9 modelsim_lib/msim/xbip_utils_v3_0_9
vmap c_reg_fd_v12_0_5 modelsim_lib/msim/c_reg_fd_v12_0_5
vmap xbip_dsp48_wrapper_v3_0_4 modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_4
vmap xbip_pipe_v3_0_5 modelsim_lib/msim/xbip_pipe_v3_0_5
vmap xbip_dsp48_addsub_v3_0_5 modelsim_lib/msim/xbip_dsp48_addsub_v3_0_5
vmap xbip_addsub_v3_0_5 modelsim_lib/msim/xbip_addsub_v3_0_5
vmap c_addsub_v12_0_12 modelsim_lib/msim/c_addsub_v12_0_12
vmap xbip_bram18k_v3_0_5 modelsim_lib/msim/xbip_bram18k_v3_0_5
vmap mult_gen_v12_0_14 modelsim_lib/msim/mult_gen_v12_0_14
vmap axi_utils_v2_0_5 modelsim_lib/msim/axi_utils_v2_0_5
vmap cordic_v6_0_14 modelsim_lib/msim/cordic_v6_0_14
vmap fifo_generator_v13_2_2 modelsim_lib/msim/fifo_generator_v13_2_2

vlog -64 -incr -sv -work xil_defaultlib  \
"E:/Xilinx/Vivado2018/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"E:/Xilinx/Vivado2018/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -64 -93 -work xpm  \
"E:/Xilinx/Vivado2018/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -64 -93 -work xbip_utils_v3_0_9  \
"../../../../prj.ip_user_files/ipstatic/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work c_reg_fd_v12_0_5  \
"../../../../prj.ip_user_files/ipstatic/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_dsp48_wrapper_v3_0_4  \
"../../../../prj.ip_user_files/ipstatic/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_pipe_v3_0_5  \
"../../../../prj.ip_user_files/ipstatic/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_dsp48_addsub_v3_0_5  \
"../../../../prj.ip_user_files/ipstatic/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_addsub_v3_0_5  \
"../../../../prj.ip_user_files/ipstatic/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work c_addsub_v12_0_12  \
"../../../../prj.ip_user_files/ipstatic/hdl/c_addsub_v12_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_bram18k_v3_0_5  \
"../../../../prj.ip_user_files/ipstatic/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work mult_gen_v12_0_14  \
"../../../../prj.ip_user_files/ipstatic/hdl/mult_gen_v12_0_vh_rfs.vhd" \

vcom -64 -93 -work axi_utils_v2_0_5  \
"../../../../prj.ip_user_files/ipstatic/hdl/axi_utils_v2_0_vh_rfs.vhd" \

vcom -64 -93 -work cordic_v6_0_14  \
"../../../../prj.ip_user_files/ipstatic/hdl/cordic_v6_0_vh_rfs.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../../../src/ip/Square_Root/sim/Square_Root.vhd" \

vlog -64 -incr -work fifo_generator_v13_2_2  \
"../../../../prj.ip_user_files/ipstatic/simulation/fifo_generator_vlog_beh.v" \

vcom -64 -93 -work fifo_generator_v13_2_2  \
"../../../../prj.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -64 -incr -work fifo_generator_v13_2_2  \
"../../../../prj.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../../../src/ip/Fifo_In8x1024_Out8x1024/sim/Fifo_In8x1024_Out8x1024.v" \
"../../../../../../src/CalCore.v" \
"../../../../../../src/Matrix.v" \
"../../../../../../src/PicSim.v" \
"../../../../../../src/PluseDection.v" \
"../../../../../../src/Sobel.v" \
"../../../../../../src/VesaDriver.v" \
"../../../../../../Sim/tb.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

