######################################################################
#
# File name : tb_wave.do
# Created on: Sat Mar 18 15:31:22 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
